"""
Configuration constants for random 'chances' and other defaults in the
anonymization pipeline.
"""

# --- Chance / probability knobs -----------------------------------

# Very small chance to add a spelling error / typo to a surrogate.
# Example: 0.002 = 0.2% per surrogate.
TYPO_IN_SURROGATE_PROB: float = 0.002

# Default behaviour flags
DEFAULT_ENABLE_RANDOM_TYPOS: bool = True


# --- Header / disclaimer knobs ------------------------------------

DEFAULT_ENABLE_HEADER: bool = True

DEFAULT_HEADER_TEMPLATE: str = (
    "##############################\n"
    "DISCLAIMER  (dutch-med-hips v{version})\n"
    "\n"
    "THIS DOCUMENT HAS BEEN AUTOMATICALLY ANONYMIZED.\n"
    "IDENTIFIABLE PATIENT HEALTH INFORMATION HAS BEEN REPLACED WITH\n"
    "SYNTHETIC SURROGATES GENERATED BY DUTCH-MED-HIPS.\n"
    "\n"
    "ALL PERSONAL DETAILS ARE ARTIFICIAL. ANY RESEMBLANCE TO REAL\n"
    "PERSONS IS ENTIRELY COINCIDENTAL.\n"
    "##############################\n"
    "\n"
)
